"""Redesign document chat_session and document_chunks models

Revision ID: 4765cd542d6b
Revises: '348ef1137f0f'
Create Date: 2026-07-25 10:56:20.198664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4765cd542d6b'
down_revision: Union[str, None] = '348ef1137f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_embedding_id'), 'document_chunks', ['embedding_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('last_message_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('display_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('storage_url', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('processing_status', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('embedding_status', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('documents', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('documents', 'total_pages')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'file_size_bytes')
    op.drop_column('documents', 'total_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('total_chunks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('documents', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'embedding_status')
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'storage_url')
    op.drop_column('documents', 'display_name')
    op.drop_column('chat_sessions', 'last_message_at')
    op.drop_index(op.f('ix_document_chunks_embedding_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
