"""Add file_hash and status to documents table

Revision ID: 348ef1137f0f
Revises: '98e940d120a2'
Create Date: 2026-07-24 17:54:29.743443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348ef1137f0f'
down_revision: Union[str, None] = '98e940d120a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('error_message', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('total_chunks', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'total_chunks')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
